<%
  # source: https://github.com/alt3/cakebox-builder/blob/f4a275ef7b258452d2c1e58e96d90cec0d7cf756/.kitchen.yml
  # Use the runlist, attributes and other settings defined in node.json to
  # ensure .kitchen.yml runs against the exact same configuration as Vagrantfile.
  require 'json'
  attributes_dot_json = 'attributes/opsworks.json'
  if File.exist?(attributes_dot_json)
    attributes = JSON.parse(File.read(attributes_dot_json))
  else
    puts "Aborting .kitchen.yml: please create a file called #{attributes_dot_json}"
    exit
  end
%>

---
driver:
  name: ec2 # instead of vagrant driver; ec2 driver requires kitchen-ec2 gem
  aws_ssh_key_id: gwu-business-1
  ssh_key: ~/.ssh/gwu-business-1.pem
  region: us-east-1
  availability_zone: us-east-1a
  #require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: amazon
    driver:
      image_id: ami-12345678
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[clubhouse::build_it]
    attributes: <%= attributes.to_json %>
