<%
  # source: https://github.com/alt3/cakebox-builder/blob/f4a275ef7b258452d2c1e58e96d90cec0d7cf756/.kitchen.yml
  # Use the runlist, attributes and other settings defined in node.json to
  # ensure .kitchen.yml runs against the exact same configuration as Vagrantfile.
  require 'json'
  #require 'pry'
  attributes_dot_json = 'attributes/opsworks.json'
  if File.exist?(attributes_dot_json)
    attributes = JSON.parse(File.read(attributes_dot_json))
    attributes.merge!({
      "mysql" => {
        "server_root_password" => ENV["MYSQL_ROOT_PASSWORD"]
      }
    })
  else
    puts "Aborting .kitchen.yml: please create a file called #{attributes_dot_json}"
    exit
  end
%>

---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[clubhouse::build]
    attributes: <%= attributes.to_json %>
